# Generated by Django 2.1.5 on 2020-09-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='enter_task',
            field=models.CharField(max_length=150, verbose_name='Enter_task'),
        ),
    ]
